<?php

function seven_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'tinymce') {
    $restricted = TRUE;
    global $user;
    $allowed_roles = array('administrator', 'super editor');
    // Test the user's role..
    foreach ($user->roles as $role) {
      if (in_array($role, $allowed_roles)) {
        $restricted = FALSE;
      }
    }
    // Restrict button visibility.
    if ($restricted) {
      $buttons = $plugins = FALSE;
      // remove the HTML code button
      $buttons = explode(',', $settings['theme_advanced_buttons1']);
      $code_key = array_search('code', $buttons);
      if ($code_key !== FALSE) {
        unset($buttons[$code_key]);
      }
      $table_key = array_search('tablecontrols', $buttons);
      if ($table_key !== FALSE) {
        unset($buttons[$table_key]);
      }
      $settings['theme_advanced_buttons1'] = implode(',', $buttons);
    }
  }
}

/*
function <THEME>_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'tinymce') {
    $restricted = TRUE;
    global $user;
    $allowed_roles = array('administrator', 'super editor');
    // Test the user's role..
    foreach ($user->roles as $role) {
      if (in_array($role, $allowed_roles)) {
        $restricted = FALSE;
      }
    }
    // Restrict button visibility.
    if ($restricted) {
      $buttons = $plugins = FALSE;
      // remove the HTML code button
      $buttons = explode(',', $settings['theme_advanced_buttons1']);
      $code_key = array_search('code', $buttons);
      if ($code_key !== FALSE) {
        unset($buttons[$code_key]);
      }
      $table_key = array_search('tablecontrols', $buttons);
      if ($table_key !== FALSE) {
        unset($buttons[$table_key]);
      }
      $settings['theme_advanced_buttons1'] = implode(',', $buttons);
    }
  }
}
*/
?>
