<?php

// Plugin definition
$plugin = array(
  'title' => t('Three column grid'),
  'category' => t('Grid: 3x6'),
  'icon' => 'threecol_grid.png',
  'theme' => 'panels_threecol_grid',
  'css' => 'threecol_grid.css',
  'regions' => array(
    'left1' => t('Left side'),
    'middle1' => t('Middle column'),
    'right1' => t('Right side'),
    'left2' => t('Left side'),
    'middle2' => t('Middle column'),
    'right2' => t('Right side'),
    'left3' => t('Left side'),
    'middle3' => t('Middle column'),
    'right3' => t('Right side'),
    'left4' => t('Left side'),
    'middle4' => t('Middle column'),
    'right4' => t('Right side'),
    'left5' => t('Left side'),
    'middle5' => t('Middle column'),
    'right5' => t('Right side'),
    'left6' => t('Left side'),
    'middle6' => t('Middle column'),
    'right6' => t('Right side')
   ),
);
