<?php

// Plugin definition
$plugin = array(
  'title' => t('Two column grid w/ 9 rows'),
  'category' => t('Grid: 2x9'),
  'icon' => 'twocol_grid.png',
  'theme' => 'panels_twocol_grid',
  'css' => 'twocol_grid.css',
  'regions' => array(
    'left1' => t('Left side'),
    'right1' => t('Right side'),
    'left2' => t('Left side'),
    'right2' => t('Right side'),
    'left3' => t('Left side'),
    'right3' => t('Right side'),
    'left4' => t('Left side'),
    'right4' => t('Right side'),
    'left5' => t('Left side'),
    'right5' => t('Right side'),
    'left6' => t('Left side'),
    'right6' => t('Right side'),
    'left7' => t('Left side'),
    'right7' => t('Right side'),
    'left8' => t('Left side'),
    'right8' => t('Right side'),
    'left9' => t('Left side'),
    'right9' => t('Right side')
   ),
);
