<?php

/**
 * @file
 * Implementation for the two column bricked layout
 */

// Plugin definition
$plugin = array(
  'title' => t('Two column multi-bricks (6 rows)'),
  'category' => t('Columns: 2'),
  'icon' => 'twocol_multibricks.png',
  'theme' => 'panels_twocol_multibricks',
  'css' => 'twocol_multibricks.css',
  'regions' => array(
    'top_row_1' => t('Top row 1'),
    'left_row_1' => t('Left row 1'),
    'right_row_1' => t('Right row 1'),
    'top_row_2' => t('Top row 2'),
    'left_row_2' => t('Left row 2'),
    'right_row_2' => t('Right row 2'),
    'top_row_3' => t('Top row 3'),
    'left_row_3' => t('Left row 3'),
    'right_row_3' => t('Right row 3'),
    'top_row_4' => t('Top row 4'),
    'left_row_4' => t('Left row 4'),
    'right_row_4' => t('Right row 4'),
    'top_row_5' => t('Top row 5'),
    'left_row_5' => t('Left row 5'),
    'right_row_5' => t('Right row 5'),
    'top_row_6' => t('Top row 6'),
    'left_row_6' => t('Left row 6'),
    'right_row_6' => t('Right row 6'),
    'bottom' => t('Bottom'),
  ),
);

